EXTRAKEY_ENABLE = yes
BOOTMAGIC_ENABLE = yes
LTO_ENABLE = yes

ENCODER_ENABLE = yes
RGBLIGHT_ENABLE = yes
WS2812_DRIVER = vendor
OLED_ENABLE = yes
I2C_ENABLE = yes

VIAL_ENABLE = yes
VIA_ENABLE = yes